apiVersion: v1
kind: Service
metadata:
  name: fox-front
  labels:
    run: fox-front
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31688
    protocol: TCP
  selector:
    run: fox-front
